version: '3'
services:
  keycloakdb:
    container_name: mariadb_keycloak
    image: mariadb:10.11
    ports:
      - 3307:3307
    environment:
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_TCP_PORT=3307
    restart: always
    volumes:
      - ./mariadb-keycloak:/var/lib/mysql
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.0
    command: ["start-dev", "--import-realm", "--log-level=INFO", "--http-port=8082", "--hostname=keycloak"]
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: keycloakdb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ISSUER_URI: http://keycloak:8082
      KEYCLOAK_FRONTEND_URL: http://keycloak:8082
      KEYCLOAK_ENABLED: "true"
    ports:
      - 8082:8082
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloakdb

  blogdb:
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogpost
    restart: always
    volumes:
      - ./mariadb-blog:/var/lib/mysql

  blog-service:
    container_name: blog-service
    image: blog_service:latest
    build: ./blog-service
    #pull_policy: always
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      DATABASE_HOST: blogdb
    depends_on:
      - blogdb

  api-gateway:
    image: api_gateway:latest
    build: api-gateway
    #pull_policy: always
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      BLOG_SERVICE_URL: http://blog-service:8081
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ISSUER_URI: http://keycloak:8082
    depends_on:
      - blogdb
      - blog-service
